## Numpy Installation & Import

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## np.array() function

In [5]:
l = [1, 2, 3, 4, 5]

In [6]:
npa = np.array(l)

In [9]:
print(type(l))
print(type(npa))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
print(l)
print(npa)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
npa.shape

(5,)

In [12]:
l.append('string')

In [13]:
npa = np.array(l)

In [19]:

print(l)
print(npa)


[1, 2, 3, 4, 5, 'string']
['1' '2' '3' '4' '5' 'string']


In [20]:
l1 = [1, 4, 9, 16]

In [21]:
l

[1, 2, 3, 4, 5, 'string']

In [22]:
l + l1

[1, 2, 3, 4, 5, 'string', 1, 4, 9, 16]

In [23]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', 'string', '1', '4', '9', '16'],
      dtype='<U11')

In [24]:
l + [20]

[1, 2, 3, 4, 5, 'string', 20]

In [25]:
l = [[1, 2], [3, 4], [3, 4]]

In [26]:
npa2d = np.array(l)

In [27]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [28]:
npa2d.shape

(3, 2)

In [29]:
npa2d = np.array(l, dtype = 'float')

In [30]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [31]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [3, 4]])

In [32]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [33]:
npa2d = npa2d.astype('str')

In [34]:
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

In [37]:
npa2d[0][0] = npa2d[0][0] + str(1)

In [38]:
npa2d

array([['1.01', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

## np.nan & np.inf functions

In [39]:
np.nan == np.nan

False

In [40]:
None == None

True

In [41]:
np.inf == np.inf

True

In [42]:
npa2d

array([['1.01', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

In [43]:
npa2d = npa2d.astype('float')

In [44]:
npa2d

array([[1.01, 2.  ],
       [3.  , 4.  ],
       [3.  , 4.  ]])

In [45]:
npa2d = npa2d.astype('int')

In [46]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [48]:
npa2d = npa2d.astype('float')
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [49]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf

In [50]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

In [51]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [52]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [53]:
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [54]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [55]:
npa2d[flag]

array([nan, inf])

In [56]:
npa2d[flag] = 0

In [57]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Statistical Operations
### (mean / var / std / median)

In [59]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [60]:
npa2d.mean()

2.0

In [61]:
npa2d.min()

0.0

In [62]:
npa2d.max()

4.0

## What is variance ?

The term variance refers to a statistical measurement of the spread between numbers in a data set.
More specifically, variance measures how far each number in the set is from the mean (average), and thus from every other number in the set.
Variance is often depicted by this symbol: σ2. Read more here https://www.investopedia.com/terms/v/variance.asp

In [63]:
npa2d.var()

2.3333333333333335

In [64]:
npa2d.std()

1.5275252316519468

In [65]:
np.median(npa2d)

2.5

## Shape() , Reshape(), Ravel() functions

In [67]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [68]:
npa2d.shape

(3, 2)

In [69]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 3., 4.]])

In [70]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 3., 4.]])

In [71]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 3., 4.])

In [73]:
npa2d.flatten()

array([0., 2., 3., 0., 3., 4.])

In [72]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Sequence, Repetitions & Random numbers

### arange(), linspace(), random(), zeroes(), ones()


In [74]:
np.arange(1, 5, dtype = 'float')

array([1., 2., 3., 4.])

In [75]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [76]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [77]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [86]:
np.zeros([2, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
'''

The expression np.zeros([1, 2, 3]) creates a 3-dimensional NumPy array filled with zeros. Let's break down what each argument means:

np.zeros: This is a NumPy function that creates an array filled with zeros.
[1, 2, 3]: This is the shape argument passed to the np.zeros function. It specifies the dimensions of the array to be created. In this case, it creates a 3D array with a shape of (1, 2, 3).
The shape (1, 2, 3) means:

The first dimension has a size of 1.
The second dimension has a size of 2.
The third dimension has a size of 3.

'''

np.zeros([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [92]:
np.ones([1, 2])

array([[1., 1.]])

In [93]:
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

In [94]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [100]:
np.random.rand(3, 3)

array([[0.20445225, 0.87811744, 0.02738759],
       [0.67046751, 0.4173048 , 0.55868983],
       [0.14038694, 0.19810149, 0.80074457]])

In [101]:
np.random.randint(0, 100, [1, 2, 3])

array([[[ 9,  7, 63],
        [61, 22, 57]]])

In [97]:
np.random.seed(1)
np.random.randint(0, 100, [3, 3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [98]:
np.random.randint(0, 100, [3, 3])

array([[ 1, 76, 71],
       [ 6, 25, 50],
       [20, 18, 84]])

In [102]:
np.unique(npa2d)

array([0., 2., 3., 4.])

In [103]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [104]:
np.unique(npa2d, return_counts= True)

(array([0., 2., 3., 4.]), array([2, 1, 2, 1], dtype=int64))

## Where()

In [105]:
arr = np.array([8,94,8,56,1,3,4,5,7])

In [106]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [107]:
np.where(arr>10)

(array([1, 3], dtype=int64),)

In [108]:
index = np.where(arr>10)

In [109]:
index

(array([1, 3], dtype=int64),)

In [110]:
arr[index]

array([94, 56])

In [111]:
index = np.where(arr<10)
arr[index]

array([8, 8, 1, 3, 4, 5, 7])

In [112]:
index = np.where(arr==10)
arr[index]

array([], dtype=int32)

In [113]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [114]:
arr[arr>10]

array([94, 56])

In [115]:
arr.max()

94

In [116]:
arr.argmax() # returns index value

1

In [117]:
arr.argmin() # returns index value

4

In [118]:
arr[arr.argmin()]

1

## File Read & Write

In [119]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [120]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [121]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [122]:
np.save('data.npy', npa2d)

In [123]:
np.load('data.npy')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [124]:
np.savez('both.npz', arr, npa2d)

In [125]:
d = np.load('both.npz')

In [126]:
d.files

['arr_0', 'arr_1']

In [127]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Concatenate & Sorting

In [128]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [129]:
np.concatenate([npa2d, npa2d], axis = 0)

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [130]:
np.concatenate([npa2d, npa2d], axis = 1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [131]:
np.concatenate([npa2d, arr], axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [132]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [133]:
npa = np.hstack([npa2d, npa2d])

In [134]:
npa

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [135]:
npa.sort()

In [136]:
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

In [137]:
npa.sort(axis = 1)
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

## Working with dates

In [138]:
d = np.datetime64('2020-12-01 23:34:23')

In [139]:
d

numpy.datetime64('2020-12-01T23:34:23')

In [140]:
d + 10

numpy.datetime64('2020-12-01T23:34:33')

In [141]:
oneday = np.timedelta64(1, 'D')

In [142]:
oneday

numpy.timedelta64(1,'D')

In [143]:
d + oneday

numpy.datetime64('2020-12-02T23:34:23')

In [144]:
oneminute = np.timedelta64(1, 'm')

In [145]:
d + oneminute

numpy.datetime64('2020-12-01T23:35:23')